---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Open Source Wearable Software and Information

<!-- badges: start -->
<!-- badges: end -->

The goal of open_source_wearables is to provide a set of links and information with respect to open-source wearable device processing and analysis.  If you would like to add links, please send a pull request.

The initial information for this repository was compiled at the [BIRS Use of Wearable and Implantable Devices in Health Research conference](https://workshops.birs.ca/events/20w5109/schedule), organized by Ashkan Ertefaie and chaired by Ciprian Crainiceanu and the following team members regarding software.

# Team Members:
- John Muschelli - Johns Hopkins, Statistician
- Jeff Goldsmith -- Columbia, Biostatistician and cheer package author
- Julia Wrobel - Colorado School of Public Health, Biostatistician	
- Luis Jaimes- Florida Polytechnic University,  Computer Science
- Brinnae Bent - Duke, Data Science & Biomedical Engineering
- Zhenke Wu - Michigan Biostatistician	
- Jessilyn Dunn- Duke, Biomedical Engineering & Bioinformatics
- Marta Karas - Johns Hopkins University, Biostatistics
- Irina Gaynanova - Texas A&M University, Statistician
- Jiawei Bai - Johns Hopkins, Biostatistician
- Larsson Omberg - Sage Bionetworks.
